[id='business-central-settings-security-policy-con_{context}']

= Security policy

Every application contains a single security policy which is used every time the system checks a permission. In security policy, the set of permissions are assigned to every role and a group.

The default security policy file is stored in the `WEB-INF/classes/security-policy.properties` under your application's `WAR` file structure.

NOTE: If the security policy is not defined then the security management feature is disabled and by default, the permission for all the resources and features is granted.

.Example security policy file template

[source]
----
# Role "admin"
role.admin.permission.perspective.read=true
role.admin.permission.perspective.read.Dashboard=false

# Role "user"
role.user.permission.perspective.read=false
role.user.permission.perspective.read.Home=true
role.user.permission.perspective.read.Dashboard=true
----

In this example, the role `admin` has all the permissions but cannot read and view the dashboard perspective, whereas the role `user` can only read and view the dashboard perspective.

Every entry defines a single permission which is assigned to a role or group. When an application starts, the default security policy file is loaded and stored in the `.niogit` directory.
