[id='rn-790-known-issues-ref']
= Known issues in {PRODUCT} {ENTERPRISE_VERSION_LONG}

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.Package list fails to populate default package for imported projects [https://issues.redhat.com/browse/RHPAM-3209[RHPAM-3209]]

Issue: When a project contains many packages, and you try to create a new asset, list of packages take some time to populate.

Steps to reproduce:

. Import a project which contains a lot of packages.
. Go to the project page.
. Click *Add Asset*.
+
The *Assets* window appears.
. Add any asset in the project.
. In the pop-up window, check the *Package* drop-down list.
+
You receive *Nothing selected* option for some time.

Expected result: Package list is populating default package for imported projects.

Actual result: Package list is not populating default package for imported projects.

Workaround:

* Make sure you have identical paths in both `src/java` and `src/resources`. When you are managing in Git repository, insert `.gitkeep` files to retain the empty folder structure.
* In the asset pop-up window, manually select the *<default>* option the *Package* drop-down list..

.Collection editor not opening for DRL based test scenarios [https://issues.redhat.com/browse/RHDM-1464[RHDM-1464]]

Issue: DRL based test scenario throws an unexpected errors when you open a collection editor for list of some datatypes.

Workaround: None.

ifdef::PAM[]
== Process Designer

.Data objects in Assignments disappear once you save the process [https://issues.redhat.com/browse/RHPAM-3212[RHPAM-3212]]

Issue: Data objects which are present in *Assignments* disappears once you save the process.

Steps to reproduce:

. Create a data object.
. Create a user task.
. Click the *Properties* icon on the upper-right side of the screen to open the *Properties* panel.
. Expand *Implementation/Execution* and select *Assignments* to open the *Data I/O* window.
. Next to *Data Inputs and Assignments*, click *Add* and select a *Source* value.
. Next to *Data Outputs and Assignments*, click *Add* and select a *Target* value.
. Close the *Assignments* and save the process.
. Open the *Assignments* sub-section.

Expected result: Source and Target fields are empty.

Actual result: Source and Target fields are set to data object.

Workaround: Deselect and select the task again.

.A new rule flow group is not reflected in business rule task properties [https://issues.redhat.com/browse/RHPAM-3195[RHPAM-3195]]

Issue: When you create a new rule flow group, the change is not reflected in business rule task's property.

Steps to reproduce:

. Create a business process.
+
Do not close the process.
. Create a `testrule.rdrl` file containing `testgroup` as ruleflow-group.
. Select *Business Rule* in created process.
. Expand *Implementation/Execution* and select *Rule Flow Group* drop-down list.

Expected result: The *Rule Flow Group* drop-down list contains ruleflow-group that is specified in DRL file. For example, `testgroup`.

Actual result: The *Rule Flow Group* drop-down list is empty.

Workaround: Deselect and then re-select business rule task.

.Edited rule flow group is not reflected in business rule task properties [https://issues.redhat.com/browse/RHPAM-3194[RHPAM-3194]]

Issue: When you edit a rule flow group, the change is not reflected in business rule task's property.

Steps to reproduce:

. Create a business process.
+
Do not close the process.
. Create a `testrule.rdrl` file containing `testgroup` as ruleflow-group.
. Open a `testrule.rdrl` file and change the `testgroup` to `testgroup-renamed`.
. Save the changes.
. Select *Business Rule* in created process.
. Expand *Implementation/Execution* and select *Rule Flow Group* drop-down list.

Expected result: The *Rule Flow Group* drop-down list contains edited `testgroup-renamed` value.

Actual result: The *Rule Flow Group* drop-down list contains `testgroup` value.

Workaround: Deselect and then re-select business rule task.

.The cursor position is different in Firefox browser when you use an inline text editor [https://issues.redhat.com/browse/RHPAM-3171[RHPAM-3171]]

Issue: When you use an inline text editor, the cursor position is different in Firefox browser in comparison with Google Chrome browser and Kogito VSCode extension.

Steps to reproduce:
Perform the following steps using both Firefox and Google Chrome browser.

. Create any node.
. Double-click to activate the node.

Expected result: The cursor is on the same position in Firefox browser in comparison with Google Chrome browser.

Actual result: The cursor is on the different position in Firefox browser in comparison with Google Chrome browser.

Workaround: None.

.Editing text using an inline text editor is displayed over *Properties* panel or expanded Palette [https://issues.redhat.com/browse/RHPAM-3172[RHPAM-3172]]

Issue: When you place any task, sub-process or text annotation in the *Properties* panel and start editing its name by using an inline text editor, the text is visible over the *Properties* panel.

Steps to reproduce:

. Create any node.
. Ensure that the *Properties* panel is open and tool palette is expanded.
. Move the node under the *Properties* panel or the expanded area of the tool palette in a way that you can still click on the node.
. Double-click the node to activate inline text editor.
. Enter any text.

Expected result: The node is not editable or the text is being shown next to the *Properties* panel or the tool palette and it is entirely visible.

Actual result: The text is visible over the *Properties* panel.

Workaround: None.

endif::[]
