[id='rn-771-known-issues-ref']
= Known issues in {PRODUCT} 7.7.1

This section lists known issues with {PRODUCT} 7.7.1.

== {OPENSHIFT}

.You can not deploy immutable {KIE_SERVER} environments on {OPENSHIFT} using Operators [https://issues.redhat.com/browse/RHPAM-2942[RHPAM-2942]]

Issue: Immutable {KIE_SERVER} environments are unable to deploy on {OPENSHIFT} using Operators.

Steps to reproduce:

. In the {PRODUCT} environment on {OPENSHIFT} using Operators, create a KIE application.
. Try to deploy immutable {KIE_SERVER} environments with the following YAML file:

----
apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhdm-production-immutable
  annotations:
    consoleName: rhdm-production-immutable
    consoleTitle: DM Production Immutable
    consoleDesc: Deploys a DM Production Immutable environment
spec:
  environment: rhdm-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhdm-kieserver-hellorules=org.openshift.quickstarts:rhdm-kieserver-hellorules:1.5.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhdm-7-openshift-image.git
            reference: master
            contextDir: quickstarts/hello-rules/hellorules
----

Expected result: Immutable {KIE_SERVER} deployment errors should not be present in the generated YAML file.

Actual result: The generated YAML file fails with the immutable {KIE_SERVER} deployment errors.

Workaround: For successful {KIE_SERVER} deployment on {OPENSHIFT} using Operators, use `useImageTags` flag.


.You can not create custom image for database [https://issues.redhat.com/browse/RHPAM-2948[RHPAM-2948]]

Issue: It is not possible to build a custom extension image for database.

Steps to reproduce:

. Download the following templates.zip file.
+
----
curl --insecure --output templates.zip http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhpam/RHPAM-7.7.1.CR1/rhpam-7.7.1-openshift-templates.zip
----

. Unzip the templates.zip file content.
+
----
unzip -q templates.zip
----

. For an example, make the image build for MySQL database.
+
----
cd templates/contrib/jdbc
make build mysql
----

Expected result: You can create and build a custom extension image for database.

Actual result: You can not build a custom extension image for database.

Workaround: Specify the following repository in the `base-db-overrides.yaml` file and start the image build again.
----
name: "quay.io/kiegroup/jboss-kie-${DATABASE_TYPE}-extension-openshift-image"
----
