[id='rn-7.11-known-issues-ref']
= Known issues in {PRODUCT} {ENTERPRISE_VERSION_LONG}

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.{CENTRAL} web application keeps on polling in an open browser once the {KIE_SERVER} is stopped [https://issues.redhat.com/browse/RHPAM-3635[RHPAM-3635]]

Issue: When you keep {CENTRAL} web application open in a browser window, once the {KIE_SERVER} is stopped, it keeps on polling the endpoint of previously running {KIE_SERVER}.

Workaround: None.

.In standalone editors, the `setContent` method implementation must receive path and content [https://issues.redhat.com/browse/RHPAM-3629[RHPAM-3629]]

Issue: In standalone editors, setContent implementation must implement the `setContent` method defined in `EditorAPI` along with path and content parameters instead of content only.

Workaround: None.

.When an executing models use an imported inputs and decision nodes, you receive an error message [https://issues.redhat.com/browse/RHDM-1733[RHDM-1733]]

Issue: The test scenario tool is unable to execute any models using an imported inputs and decisions nodes. The auto generated decision table columns reflects the incorrect values.

Workaround: None.

.Method calls does not support template keys [https://issues.redhat.com/browse/RHDM-1729[RHDM-1729]]

Issue: If you remove one of the action call from Business Rule Language (BRL) action column, the generated DRL file is updated incorrectly.

Steps to reproduce:

. Import the *Mortgages* sample project.
. Replace the original content of *LoanApplication* with the [https://issues.redhat.com/secure/attachment/12521425/12521425_LoanApplication.java[LoanApplication.java]].
. Replace the original content of *Pricing Loans* with the `Pricing loans (1).gdst` file. (This file is attached in the [https://issues.redhat.com/browse/RHDM-1729[RHDM-1729]] issue).
. Validate `Pricing loans (1).gdst` file.
. Go to *Columns* tab, select *Action columns*.
. For *call functions* option, click *Edit*.
. Remove *Call [application.addExplanation]* and *Call [application.deadline]* and click *Finish*.

Workaround: None.

.The Business Rule Language (BRL) columns does not support the conversion of method call data type [https://issues.redhat.com/browse/RHDM-1696[RHDM-1696]]

Issue: When a guided decision table is converted into XLS decision table, the menthod calls with `String` or `Date` data type arguments are not converted correctly.

Steps to reproduce:

. Import the *Mortgages* sample project.
. Replace the original content of *LoanApplication* with the [https://issues.redhat.com/secure/attachment/12517646/12517646_LoanApplication.java[LoanApplication.java]].
. Replace the original content of *Pricing Loans* with the `Pricing loans (1).gdst` file. (This file is attached in the [https://issues.redhat.com/browse/RHDM-1696[RHDM-1696]] issue).
. Convert the *Pricing Loans* into XLS table.
. Open the converted XLS table and switch to *Source* tab.
+
The `addExplanation` method assumes `exp` is a variable instead of constant. The `deadline` method assumes `08-Mar-2021` is a date, but it is a string. Some wrapper modules are needed for converting `String` into `Date`.

Expected result: Validation of the XLS table succeeds.

Actual result: Validation of the XLS table fails.

Workaround: None.

.The guided decision table sorting functionality does not work in decision table graph [https://issues.redhat.com/browse/RHDM-1664[RHDM-1664]]

Issue: The guided decision table sorting functionality does not work in decision table graph. The merged view of table is not sorted properly.

Steps to reproduce:

. Import the *Mortgages* sample project.
. Import the `second small table.gds` file attached in the [https://issues.redhat.com/browse/RHDM-1664[RHDM-1664]] issue.
. Create a decision table graph containing *Pricing Loans* column with the `second small table.gds` file.
. Try to sort the *second small table*.

Workaround: None.

.The guided decision table merged view throws an error [https://issues.redhat.com/browse/RHDM-1663[RHDM-1663]]

Issue: The merged view of the guided decision table is not sorted properly. You receive an unexpected system error.

Workaround: None.

.In the guided decision table, sorting functionality does not work for `LocalDate` [https://issues.redhat.com/browse/RHDM-1662[RHDM-1662]]

Workaround: None.

ifdef::PAM[]

== Process Designer

.An icon used to open subprocess is same as the forms icon [https://issues.redhat.com/browse/RHPAM-3659[RHPAM-3659]]

Issue: In user task, an icon used to open subprocess in reusable subprocess is same as the icon used for generating forms.

Steps to reproduce:

. Create a reusable subprocess.
. Check the *Open sub-process* icon.

Expected result: The open subprocess icon is unique and not similar to the forms icon.

Actual result: The open subprocess is same as the icon used for generating forms.

Workaround: None.

.A subprocess linked to itself does not perform any action [https://issues.redhat.com/browse/RHPAM-3658[RHPAM-3658]]

Issue: When a process is linked to itself which means the process where a reusable subprocess is placed and you click the *Open sub-process*, nothing happens.

Steps to reproduce:

. Create a *testing-process* business process.
. Drag and drop a reusable subprocess to canvas.
. Set the *Called Element* property to *testing-process* process.
. Click *Open sub-process* icon in reusable subprocess.

Expected result: An alert panel is expected with the *A process is already open* message.

Actual result: No action is performed.

Workaround: None.

.A process from different projects opened from BPMN editor displays an incorrect breadcrumb navigation panel [https://issues.redhat.com/browse/RHPAM-3657[RHPAM-3657]]

Issue: If a process is placed in a different project and it is linked to a reusable subprocess, and when you open that project, the breadcrumb navigation panel remains unchanged.

Steps to reproduce:

. Create a *Project A* project.
. Create a *Process-A* business process in *Project A*.
. Create a *Project B* project.
. Create a *Process-B* business process in *Project B*.
. Drag and drop a reusable subprocess to canvas.
. Set the *Called Element* property to *Process-A* business process.
. Click *Open sub-process* icon in reusable subprocess.

Expected result: The linked process is opened and the breadcrumbs displays the correct project.

Actual result: The linked process is opened, but the breadcrumbs displays the wrong project.

Workaround: None.

.A process instance *Diagram* tab does not display the instance count badges when you are navigating between parent or child process [https://issues.redhat.com/browse/RHPAM-3634[RHPAM-3634]]

Issue: When you are navigating between a parent or child process, the instance count badges are not rendered after the navigation. But when you switch between the *Logs* tab to *Diagram* tab, instance count badges appears again.

Steps to reproduce:

. Create and start a parent and child process pair.
. Keep the child process running by placing the human task.
. Navigate either through panel or *Diagram* tab to the child subprocess.
+
The instance count badges are missing.
. Navigate to *Logs* tab and go back to *Diagram* tab.
+
The instance count badges appears again.

Workaround: None.

.BPMN designer fails to parse the Work Item Definition file with incorrect properties [https://issues.redhat.com/browse/RHPAM-3619[RHPAM-3619]]

Issue: When a Work Item Definition (WID) file contains something unexpected but a valid MVEL expression, the BPMN designer fails to parse it with incorrect properties.

Steps to reproduce:

. Create a KJAR project in VSCode extension.
. In global folder, add WID definitions.
. Add a property with *mavenDependecy* or *dependency* name.

Expected result: The properties are parsed and the task from WID file present in the palette.

Actual result: The properties are not parsed the task from WID file is not present in the palette.

Workaround: Remove the unrecognized properties from the WID file.

.In BPMN designer, VSCode workspace with multiple folders breaks the WID resolution [https://issues.redhat.com/browse/RHPAM-3618[RHPAM-3618]]

Issue: In VSCode workspace, when you use the *Add new Folder to workspace* option, the resolution breaks itself. Multiple folders created in VSCode workspace breaks the work item definitions.

Steps to reproduce:

. Create a KJAR project in VSCode extension.
. Add a WID definition to global folder located in the root of the workspace or in the directory as a process.
. Check the process contains custom tasks in palette.
. Use the *Add new Folder to workspace* option.
. Open the BPMN editor and check the palette for custom tasks.
+
Custom tasks are not present.

Expected result: When there are multiple folders in VSCode workspace, custom tasks are resolved in BPMN designer.

Actual result: When there are multiple folders in VSCode workspace, custom tasks are not resolved in BPMN designer.

Workaround: Remove the extra folder form workspace.

.In BPMN designer, an unknown custom tasks makes the diagram explorer empty [https://issues.redhat.com/browse/RHPAM-3606[RHPAM-3606]]

Issue: In BPMN designer, when you add an unknown custom tasks, the diagram explorer fails to display any nodes.

Steps to reproduce:

. Create a case project.
. Navigate to the project settings and install `ServiceTask` and `JMSSendTask`.
. Save the changes.
. Create a case definition in the project with `ServiceTask` and `JMSSendTask`.
. Save the changes.
. Close the case project.
. Navigate to the project settings and uninstall `ServiceTask` and `JMSSendTask`.
. Save the changes.
. Open a case project and click *Explore Diagram*.

Expected result: The diagram explorer contains all the nodes placed on a canvas.

Actual result: The diagram explorer is empty.

Workaround: If you want to use the *Explore Diagram*, either remove `ServiceTask` and `JMSSendTask` from canvas or install appropriate work item definitions.

.The *Properties* panel expansion shifts the scroll bar [https://issues.redhat.com/browse/RHPAM-3532[RHPAM-3532]]

Issue: If you scroll down to check tan entire editor, input any strings and expand the *Properties* panel, the position of the main vertical scroll bar is changed.

NOTE: This issue is applicable only to Firefox browser and not applicable to Chrome browser.

Steps to reproduce:

. Create a business process.
. Create a general service task.
. Open the *Properties* panel and scroll down to very bottom to check the *On Exit Action* property.
. Expand the *Properties* panel.

Expected result: The main scroll bar keeps its position when you resize the panel.

Actual result: The main scroll bar of the *Properties* panel is shifted. As a result, the position of properties in the *Properties* panel is changed.

Workaround: None.

.The generated `.bpmn` file lacks the `structureRef` for `endMessageType` [https://issues.redhat.com/browse/RHPAM-3437[RHPAM-3437]]

Issue: When you create a process in BPMN editor, the `structureRef` for a message is not present.

Steps to reproduce:

. Create a new business process.
. Create a process variable.
. Create a start, intermediate catching, throwing or end message event.
. Set the message property of message event to any value.
. Create a *Data Assignment* for this message event with any name, set the data type as `Boolean`, and target to newly created process variable.
. Save the changes and check the source code of the process.

Expected result: The generated `.bpmn` file contains the `structureRef` for all the defined messages with a value defined in data assignments.

Actual result: The generated `.bpmn` file lacks the `structureRef` for with `id: $MESSAGE_NAME_Type`.

Workaround: None.

.The JavaScript language in an *On Entry Action* property throws an error after changing a node to multiple instances [https://issues.redhat.com/browse/RHPAM-3409[RHPAM-3409]]

Issue: When the language in *On Entry Action* property is to JavaScript, and then you change the node to *Multiple Instance*, you receive an unexpected system error.

Steps to reproduce:

. Create a new business process.
. Create a user task and set it to the *Multiple Instance* property.
. Input any string to *On Entry Action* or *On Exit Action*.
. Select the JavaScript language.
. Select the *Multiple Instance* check box.

Expected result: You do not receive any error either in UI or in server log.

Actual result: You receive an unexpected system error.

Workaround: None.

endif::[]

== DMN designer

.Unable to create a new `.scesim` file in VSCode instance when a workspace contains multiple folders [https://issues.redhat.com/browse/RHPAM-3621[RHPAM-3621]]

Issue: When there are multiple folders within one workspace, the scenario simulation editor fails at creating a new scenario for a given DMN model.

Steps to reproduce:

. Create a VSCode workspace with a single folder in it.
. Create a valid DMN file.
. Create a `.scesim` file for the newly created DMN file.
. Add a new folder in a VSCode workspace.
. Create a different `.scesim` file for the same DMN file.

Workaround: Keep just a single folder inside your workspace. If you want to work on multiple projects, open the projects in a separate VSCode instances each.

.A decision service is missing `encapsulatedDecisions` element for transitive dependencies in a model with multiple decision requirements diagrams [https://issues.redhat.com/browse/RHDM-1732[RHDM-1732]]

Issue: When a model contains multiple decision requirements diagrams (DRD) and tries to reuse a decision component by adding it into a decision service node, the resulting decision service node does not contain any `encapsulatedDecisions` definitions for its transitive dependencies.

Steps to reproduce:

. Define multiple DRDs.
. In one DRD, define some decisions with transitive dependency on a decision.
. In another DRD, define decision services and reuse the previously created decision component.
+
Do not duplicate the transitive dependency.
. Build and deploy your project.
. Complete any of the following tasks:

* Evaluate the decision to verify the error reported in description.
* Check the `dmn` source code and verify that `inputData` from decision service is missing or not.
* Check the decision service details in the *Properties* panel.

Workaround: The transitive decisions need to be part of the `encapsulatedDecisions` section of the modeled decision service.

.DMN editor removes the edges for duplicate decision nodes on canvas [https://issues.redhat.com/browse/RHDM-1714[RHDM-1714]]

Issue: An issue occurs with the edges handling when you duplicate a decision component in a canvas. The edges that are originally modeled are either shifted or removed.

Steps to reproduce:

. Create a decision node A link to another decision node B.
. Drag the decision node A from *Decision Components* panel on canvas.
. Create an input node and link it to the duplicated decision node A.
. Click *Save*.
. Reopen the project.
+
The link from input node is now connected to the original decision node A while the duplicated decision node has no links at all.

Workaround: Keep a single occurrence of Decision component per DRD.

.In DMN editor, the suggestion box does not parse the function arguments [https://issues.redhat.com/browse/RHDM-1661[RHDM-1661]]

Issue: The DMN editor does not parse any helpful suggestions when you are writing literal expressions.

Steps to reproduce:

. Open a DMN editor.
. Add a decision node.
. Set the expression as *Literal expression*.
. Enter `date(2011 | , , )` expression and check the suggestion box.

Workaround: None.

.In DMN editor, the suggestion box parse the result of an addition as a list instead of number [https://issues.redhat.com/browse/RHDM-1660[RHDM-1660]]

Issue: When you parse an addition to a literal expressions, the DMN editor suggests functions returning list instead of a number.

Steps to reproduce:

. Open a DMN editor.
. Add a decision node.
. Set the expression as *Literal expression*.
. Enter `sum([1]) + sum([2])` expression and check the suggestion box.

Workaround: None.

.In DMN editor, the suggestion box fails to recognize variables [https://issues.redhat.com/browse/RHDM-1658[RHDM-1658]]

Issue: When you parse the `number` type to a literal expressions, the DMN editor fails to recognize variables.

Steps to reproduce:

. Open a DMN editor.
. Add a decision node.
. Set the expression as *Literal expression*.
. Enter `numeric variable +` expression and check the suggestion box.

Workaround: None.

.In DMN editor, the suggestion box fails to recognize duration expression [https://issues.redhat.com/browse/RHDM-1656[RHDM-1656]]

Issue: When you try to parse the duration expression, the DMN editor suggests string functions instead of duration functions.

Steps to reproduce:

. Open a DMN editor.
. Add a decision node.
. Set the expression as *Literal expression*.
. Enter `date( "2012-12-25" ) - date( "2012-12-24" )` expression and check the suggestion box.

Workaround: None.

.In DMN editor, the suggestion box fails to recognize date expression [https://issues.redhat.com/browse/RHDM-1654[RHDM-1654]]

Issue: When you try to parse the date expression, the DMN editor suggests string functions instead of date functions.

Steps to reproduce:

. Open a DMN editor.
. Add a decision node.
. Set the expression as *Literal expression*.
. Enter `date(date and time( "2012-12-25T11:00:00Z" ))` expression and check the suggestion box.

Workaround: None.

.In DMN editor, the suggestion box fails to recognize the negated boolean expression [https://issues.redhat.com/browse/RHDM-1652[RHDM-1652]]

Issue: When you try to parse the negated boolean expression, the DMN editor offers different suggestions which are not related to the given expression.

Steps to reproduce:

. Open a DMN editor.
. Add a decision node.
. Set the expression as *Literal expression*.
. Enter `false` or `not false` expression and check the suggestion box.

Workaround: None.
