[id='rn-known-issues-ref']
= Known issues in {PRODUCT} 7.8.0

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.An error message about missing {KIE_SERVER} configuration on dashbuilder runtime must be improved [https://issues.redhat.com/browse/RHPAM-3058[RHPAM-3058]]

Issue: The dashbuilder runtime user interface currently throwing a wrong error message about missing {KIE_SERVER} configuration.

Steps to reproduce:

* Start {CENTRAL}.
* Try to import the {KIE_SERVER} dataset on dashbuilder runtime.

Expected result: The dashbuilder runtime displays an error message with missing or wrong {KIE_SERVER} system property.

Actual result: The dashbuilder runtime is not displaying an error message with missing or wrong {KIE_SERVER} system property.

Workaround: None.

.The `dodeploy` file is not available in the dashbuilder runtime distribution [https://issues.redhat.com/browse/RHPAM-3031[RHPAM-3031]]

Issue: The dashbuilder runtime application comes as a zip file which contains a `dashbuilder-runtime.war`. This folder contains all the files which are required for the deployment. Also, the `dashbuilder-runtime.war.dodeploy` file is not available in that zip file.

Workaround: Update zip file by adding `dashbuilder-runtime.war.dodeploy` file as the copy of the folder `dashbuilder-runtime.war`. Alternatively, the distribution must be a war file and you can directly copy to the deployments folder.

.When you export the dashbuilder related data, gradual export displays internal data sources [https://issues.redhat.com/browse/RHPAM-3021[RHPAM-3021]]

Issue: When you export the dashbuilder related data, gradual export displays internal data sources for user selection. In fact, it should display the public data sets only.

Workaround: None.

.In Guided decision table, the verifier feature does not work properly for columns with the `Date` data type [https://issues.redhat.com/browse/RHDM-1399[RHDM-1399]]

Issue: In Guided decision table, the verifier feature throws an error when you open a table that contains a specific combination of template keys in the actions column. These template keys are associated with the `Date` data type.

Workaround: None.

.You can not select the cell of the guided decision table [https://issues.redhat.com/browse/RHDM-1398]

Issue: You can not select the data cell of the guided decision table with the help of a mouse.

Steps to reproduce:

* In Business Central, go to *Menu → Design → Projects* and click *Mortgages*.
* Open the `Pricing loans` guided decision table.
* Click the data cell of the guided decision table.

Expected result: You can select the data cell of the guided decision table with the help of a mouse.

Actual result: You can not select the data cell of the guided decision table with the help of a mouse.

Workaround: You can select the header cell using mouse and then navigate into the data cells with help of keyboard arrow keys.

.You can not use undo and redo keyboard shortcut keys in the grid editor [https://issues.redhat.com/browse/RHDM-1397[RHDM-1397]]

Issue: You can not perform undo (Ctrl+Z) or redo (Ctrl+Shift+Z) operation in the grid editor with the help of keyboard shortcut keys.

Steps to reproduce:

* Create a new DMN diagram.
* Add two decision nodes.
* Press Ctrl+Z.
+
One decision node is removed.
* Navigate to the grid editor of the remaining node.
* Add some context entries.
* Press Ctrl+Z.
+
The same context is present.

Expected result: You can use undo and redo keyboard shortcut keys in the grid editor

Actual result: You can not use undo and redo keyboard shortcut keys in the grid editor

Workaround: The *Undo* button from toolbar works correctly.

.You can not convert the rule names from guided decision table into spreadsheet decision table [https://issues.redhat.com/browse/RHDM-1396[RHDM-1396]]

Issue: You can not convert the rule names from guided decision table into spreadsheet decision table (XLS).

Steps to reproduce:

* In Business Central, go to *Menu → Design → Projects* and click *Mortgages*.
* Open the `Pricing loans` guided decision table.
* In *Columns* tab, display the rule name column.
* In *Model* tab, set some custom rule names.
* Save the guided decision table.
* Convert the guided decision table into `XLS` file via toolbar button.
* Open the generated `XLS` file, click *Source* tab, and verify the rule names.

Expected result: Custom rule names are correctly converted from guided decision table into spreadsheet decision table (XLS).

Actual result: Custom rule names are not correctly converted from guided decision table into spreadsheet decision table (XLS).

Workaround: None.

ifdef::DM[]

.Custom export functionality is not supported in the {PRODUCT}

Issue: Custom export functionality requires at least one page to export the dashbuilder related data. In {PRODUCT}, you can not create any custom pages.

Workaround: None.

endif::[]

ifdef::PAM[]
== Process Designer
.When you create a text annotation from main palette, you receive a system error message [https://issues.redhat.com/browse/RHPAM-3052[RHPAM-3052]]

Issue: When you try to create a text annotation from main palette, you receive a system error message

Steps to reproduce:

* Create a process.
* Drag and drop a text annotation from main palette without expanding the palette.

Expected result: Text annotation is created without any system error.

Actual result: Text annotation is not created.

Workaround: Create a text annotation from expanded palette only.

.When you morph to an event gateway, you can not delete the connected nodes and save the process [https://issues.redhat.com/browse/RHPAM-3036[RHPAM-3036]]

Issue: When you morph to an event gateway, you can not delete the connected nodes and save the process. Also, it is not possible to delete the sequence flows. You receive an error message.

Steps to reproduce:

* Create a process with a parallel gateway.
* Append any node expect Timer and Text Annotation.
* Morph that gateway to event gateway.
* Try to delete any connected nodes, sequence flow or the gateway itself.
* Save the process.

Expected result: You can delete the connected nodes, sequence flow. You can save the process. Also, you receive a warning message in case the process is not executable.

Actual result: You can not delete the connected nodes, sequence flow. Also, you can not save the process.

Workaround: Change a gateway type back to its previous gateway type using morphing toolbox menu. For example, try to change the event gateway back to parallel gateway.
endif::[]

== DMN Designer

.When you include a PMML 4.4 model into a DMN model and then save or validate the model, DMN throws an error [https://issues.redhat.com/browse/RHDM-1400[RHDM-1400]]

Issue: You can not include a PMML 4.4 model into a DMN model, DMN model throws an error.

Steps to reproduce:

* Create a new empty project in {CENTRAL}.
* Create an empty DMN model.
* Import one PMML asset with the 4.4 version into the project.
* Open the DMN model.
* Select the *Included Models* tab.
* Click the *Include Model* and select the PMML 4.4 model.
* Click *Include*.

Expected result: You can include a PMML 4.4 model into a DMN model.

Actual result: You can not include a PMML 4.4 model into a DMN model.

Workaround: None

.When you try to invoke a Business Knowledge Model (BKM) function from included DMN model, the validation fails [https://issues.redhat.com/browse/RHDM-1395[RHDM-1395]]

Issue: You can not call the BKM function imported from another DMN model, which is aliased with the name containing `.` characters. If you try to invoke that function, the validation fails.

Steps to reproduce:

* Create an empty `Salary.dmn` DMN model.
* Create an another empty `WorkingHours.dmn` DMN model.
* Import `WorkingHours.dmn` DMN model into `Salary.dmn` DMN model.
* Set an alias for `WorkingHours.dmn` model by including `.` character. For example, `working.hours.model`.
* Validate the model. You receive an error message.

Workaround: None

== {PLANNER}

.In Constraint Streams API, the performance of incremental score calculations is degraded using `groupBy()` method [https://issues.redhat.com/browse/RHDM-1385[RHDM-1385]]

Issue: When you use the `groupBy()` method in Constraint Streams API, the the performance of incremental score calculations is degraded on high level.

Workaround: You can use the DRL score calculations.

== {OPENSHIFT}

.The {CENTRAL} pod fails to start when the `known_host` file is missing from the githook secret [https://issues.redhat.com/browse/RHPAM-3056[RHPAM-3056]]

Issue: The {CENTRAL} pod fails to start and remains stuck at *Container Creating* status if the `known_host` file is missing from the githook secret.

Steps to reproduce:

* Create the following post-commit script.
+
----
cat post-commit
#!/usr/bin/sh
echo "running post-commit git hook"
git clone git@github.com:Sgitario/kjar-examples.git
----

* Upload this post-commit file into the Openshift.
+
----
oc create configmap githook-post-commit --from-file=post-commit=post-commit
----

* Create the githook secret.
+
----
oc create secret generic githook-ssh-key-secret --from-file=id_rsa=/mypath/.ssh/id_rsa
----

Expected result: {CENTRAL} pod does not fails even after the githook secret is missing some configurations.

Actual result: {CENTRAL} pod fails to start remains stuck at *Container Creating* status.

Workaround: Specify the following `known_host` file and create the secret again.

----
oc create secret generic githook-ssh-key-secret --from-file=id_rsa=test_manual/.ssh/id_rsa --from-file=known_hosts=test_manual/.ssh/known_hosts
----
