[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

=== {CENTRAL} UI updates
The following list provides a summary of the Business Central UI updates:

* Ability to customize rule name and view Rule Name column in a guided decision table
* Ability to specify default values for the new rows in a guided decision table
* Ability to export a guided decision table to excel
* Ability to process multiple worksheet decision tables in a spreadsheet workbook

=== Code completion for FEEL expressions improvement in Decision Model and Notation (DMN) designer
When typing a FEEL expression in the boxed literal expression editor, you can now see node names appear as suggestions that you can apply to complete the expression if required.

=== Support for metadata attributes in BPMN modeler
You can now use *Metadata Attributes* property and manage the generic attributes of a business process.

ifdef::PAM[]

=== Support for variable tagging in processes
The {PRODUCT} process designer now supports variable tagging for the business processes.

=== Business Keys for case management
{PRODUCT} {ENTERPRISE_VERSION} includes additional support for further customizing the case identifier generation. For more information, see {URL_DESIGNING_CASES}[_{DESIGNING_CASES}_].

endif::PAM[]

=== Support for Security Management actions and updating space components using the REST API
You can now perform *Security Management* actions and update space components using the REST API:

* Update `description`, `owner`, and `defaultGroupId` of a space
+
[source]
----
[PUT] /spaces
----

* Return all groups in {CENTRAL}
+
[source]
----
[GET] /groups
----

* Create a group in {CENTRAL}
+
[source]
----
[POST] /groups
----

* Delete a specified group from {CENTRAL}
+
[source]
----
[DELETE] /groups/{groupName}
----

* Returns all roles in {CENTRAL}
+
[source]
----
[GET] /roles
----

* Returns all users in {CENTRAL}
+
[source]
----
[GET] /users
----

* Return all groups assigned to a specified user
+
[source]
----
[GET] /users/{userName}/groups
----

* Return all roles assigned to a specified user
+
[source]
----
[GET] /users/{userName}/roles
----

* Create a specified user with specified roles and groups
+
[source]
----
[POST] /users
----

* Change the password of a specified user
+
[source]
----
[Post] /users/{userName}/changePassword
----

* Delete a specified user from {CENTRAL}
+
[source]
----
[DELETE] /users/{userName}
----

* Override the existing groups assigned to a specified user with new groups
+
[source]
----
[POST] /users/{userName}/groups
----

* Override the existing roles assigned to a specified user with new roles
+
[source]
----
[POST] /users/{userName}/roles
----

* Return all permissions granted to a specified group
+
[source]
----
[GET] /groups/{groupName}/permissions
----

* Return all permissions granted to a specified role
+
[source]
----
[GET] /roles/{roleName}/permissions
----

* Return all permissions granted to a specified user
+
[source]
----
[GET] /users/{userName}/permissions
----

* Update the permissions of a specified group
+
[source]
----
[Post] /groups/{groupName}/permissions
----

* Update the permissions of a specified role
+
[source]
----
[Post] /roles/{roleName}/permissions
----

=== Support for dashbuilder runtime
Dashbuilder runtime is a new add-on standalone web application and it is distributed as a `WAR` to run the dashboards on {EAP}. If you have access to dashbuilder runtime, you can explore the dashboards created in {CENTRAL}. The following list provides a summary of dashbuilder runtime:

* After creating dashboards using datasets and pages, you can export these dashboards from {CENTRAL} using custom export.
* You can import, access, and run the dashboards which are exported from {CENTRAL} in a dashbuilder runtime.
* Dashbuilder runtime accesses the {KIE_SERVER} REST API to run the queries from imported {KIE_SERVER} datasets.

=== Test Scenarios
The test scenarios designer in {CENTRAL} now supports the enumeration data type in rule-based test scenarios.

=== Prediction service for task augmentation
The prediction service for task augmentation is integrated with Open Data Hub Artificial intelligence (AI) and Machine learning (ML) services. There is a proof of concept (POC) available for Fraud Detection.

=== Full support for process instance migration
Users can apply their migration plan to the running process instance in a specific KIE Server. For more information, see {URL_MANAGING_PROCESSES}[_{MANAGING_PROCESSES}_].

=== Viewing reusable subprocess from the parent process
{PRODUCT}
{ENTERPRISE_VERSION} provides support for viewing a subprocess by clicking on the parent process diagram. Users can easily view and explore pending tasks within the subprocess.
For more information, see {URL_DESIGNING_BUSINESS_PROCESSES}[_{DESIGNING_BUSINESS_PROCESSES}_].

== {DECISION_ENGINE_CAP}

=== Executable model lambda externalization optimization
The new executable model optimization improves memory consumption at runtime. It rewrites how the lambdas are generated that are used in the executable model. To disable the lambda externalization, use the following key:

[source]
----
 -Ddrools.externaliseCanonicalModelLambda=false
----

ifdef::PAM[]

== {PROCESS_ENGINE_CAP}

=== Start a business process from a specific node
You can now start a business process from a specific node after the business process is terminated.

=== New notification listener properties
{PRODUCT} {ENTERPRISE_VERSION} includes two new jBPM properties that are used to enable and disable notification listeners.

=== OR operator for custom queries
{PRODUCT} {ENTERPRISE_VERSION} includes an OR operator to define query filters.

endif::PAM[]

== Support for {EAP_LONG} {EAP_VERSION}
You can now install {PRODUCT} on {EAP_LONG} {EAP_VERSION}. For more information about installing {PRODUCT} on {EAP_LONG} {EAP_VERSION}, see {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].

== Support for {JWS} {JWS_VERSION}
You can now install {PRODUCT} on {JWS} {JWS_VERSION}. For more information about installing {PRODUCT} on {JWS} {JWS_VERSION}, see {URL_INSTALLING_ON_JWS}[_{INSTALLING_ON_JWS}_].

== Support for MySQL 8.0
You can now deploy {PRODUCT} with a MySQL 8.0 data source. For more information, see {URL_INSTALLING_ON_EAP}/index#eap-data-source-add-proc[Configuring JDBC data sources for KIE Server] in the {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_] guide.

== {PLANNER}

=== {PLANNER} Constraint Streams API
The Constraint Streams API is now fully supported.

=== {KIE_SERVER} Task Assigning
{KIE_SERVER} optimization and business process management capabilities are integrated so human tasks that belong to a process can be assigned to users as part of an optimized plan.

=== Vehicle Routing Planner
The Vehicle Routing Planner includes user interface improvements, server error reporting, and a new run script. For more information , see the

== {OPENSHIFT}

=== Support for deployment on {OPENSHIFT} 4.5
You can now deploy {PRODUCT} on {OPENSHIFT} 4.5.

=== Custom image creation for {KIE_SERVER} on {OPENSHIFT}
You can now create and use custom {KIE_SERVER} images with additional JAR or RPM packages.
For more information about creating custom images, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/customimage-con_openshift-operator#customimage-con_openshift-operator[Creating custom images for {KIE_SERVER}] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

=== SSH authentication for Git hooks on {OPENSHIFT} 4.x
When configuring Git hooks for {CENTRAL} on {OPENSHIFT} 4.x, you can now configure SSH authentication for access to custom Git repositories.
For more information about preparing Git hooks for deployment, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/dm-openshift-prepare-con#githooks-prepare-proc-openshift-operator[Preparing Git hooks] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

ifdef::PAM[]

=== New database server versions supported on {OPENSHIFT}

* When deploying {PRODUCT} on {OPENSHIFT}, you can now use MySQL version 8 as a part of the deployment.
* {PRODUCT} deployments on {OPENSHIFT} now support MySQL version 8 as an external database server.
* {PRODUCT} deployments on {OPENSHIFT} now support PostgreSQL 11 and EnterpriseDB Postgres Advanced Server 11 as external database servers for the {KIE_SERVER}.
* {PRODUCT} deployments on {OPENSHIFT} now support Oracle Database 19c as an external database server for the {KIE_SERVER}.
* {PRODUCT} deployment on {OPENSHIFT} now supports Microsoft SQL Server 2017 as an external database server for the {KIE_SERVER}.

=== Support for deploying production {PRODUCT} environments on {OPENSHIFT} 4.x without ReadWriteMany access to a persistent volume
You can now deploy a production environment for {PRODUCT} on {OPENSHIFT} 4.x with a simplified version of {CENTRAL} monitoring that does not require ReadWriteMany access to a persistent volume.
For more information about deploying {PRODUCT} on {OPENSHIFT} 4.x, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/operator-con#operator-environment-deploy-assy[Deploying a {PRODUCT} environment using the operator] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

=== Process instance migration service on {OPENSHIFT} 4.x
You can now deploy the Process Instance Migration (PIM) service on {OPENSHIFT} 4.x. You can use the PIM service to define the migration between two different process definitions, known as a migration plan. You can then apply the migration plan to the running process instances in a specific {KIE_SERVER}.
For more information about deploying {PRODUCT} on {OPENSHIFT} 4.x, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/operator-con#operator-environment-deploy-assy[Deploying a {PRODUCT} environment using the operator] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

endif::PAM[]
