[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

=== New standalone BPMN and DMN editors

{PRODUCT} now provides standalone editors for Business Process Model and Notation (BPMN) process models and Decision Model and Notation (DMN) decision models. The standalone editors enable you to view and design BPMN and DMN models embedded in your web applications. The read-only mode for standalone BPMN editor is not supported in {PRODUCT} 7.10.0.

The standalone editors are distributed in a self-contained library that provides an all-in-one JavaScript file for each editor. The JavaScript file uses a comprehensive API to set and control the editor. You can install the standalone editors in three ways:

* Use hosted JavaScript files directly
* Download each JavaScript file manually
* Use the NPM package

For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-dmn-models[_{DMN_MODELS}_] and {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

=== Support for DMN 1.1 and 1.3 assets in DMN designer

You can now use the DMN designer in {CENTRAL} to open DMN 1.1 and 1.3 assets. Any DMN 1.1 and 1.3 models (do not contain DMN 1.3 features) that you import into {CENTRAL}, open in the DMN designer, and save are converted to DMN 1.2 models. For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-dmn-models[_{DMN_MODELS}_].

=== Support for VSCode extension

{PRODUCT} now provides support for VSCode extension enabling you to view and design BPMN and DMN models in Visual Studio Code (VSCode). The VSCode extension in {PRODUCT} requires VSCode 1.46.0 or later.

You can install the {PRODUCT} VSCode extension using:

* VSCode user interface

. Open *Extensions* menu option.
. Search for and install *Red Hat Business Automation Bundle* extension.

* Terminal

. Launch VSCode Quick Open.
. Enter the following command and press *Enter*.
+
`ext install redhat.vscode-extension-red-hat-business-automation-bundle`

For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-dmn-models[_{DMN_MODELS}_] and {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

=== Test scenarios

The test scenarios designer in {CENTRAL} is now available with the new features supported in {PRODUCT} {PRODUCT_VERSION}.

* In the test scenario editor, you can now perform the undo and redo operations from the *Settings* panel. Also, the warning pop-up is indicated when you save or discard any changes from the *Settings* panel.

* In rule-based test scenarios, it is now possible to use the following new java classes as data objects:

** LocalDateTime
** LocalTime
** BigDecimal
** BigInteger

* It is now possible to use the following classes to create and manage the list values for the data objects:

** Byte
** Character
** Float
** Long
** Short
** LocalDateTime
** LocalTime
** BigDecimal
** BigInteger

=== New parameter list for Decision Services

{PRODUCT} {ENTERPRISE_VERSION} includes a new *Decision Service details* section in the DMN editor properties panel containing a read-only list of *Input Data*, *Encapsulated Decisions*, and *Output Decisions*.

For more information, see {URL_GETTING_STARTED_DECISION_SERVICE}#assembly-getting-started-decision-services[_{GETTING_STARTED_DECISION_SERVICE}_].

ifdef::PAM[]

=== Dashbuilder Runtime

The following list provides a summary of Dashbuilder Runtime updates:

* It is now possible to automatically deploy the dashboards from {CENTRAl} on dashbuilder runtime. {CENTRAl} is linked to dashbuilder runtime with the help of gradual export feature. You can select datasets and pages, but instead of downloading a `ZIP` file, you can click the *Open* button. When you click the *Open* button, the selected data is exported and dashbuilder runtime updates the model content when it is opened.
+
You can use `dashbuilder.runtime.multi`, `dashbuilder.runtime.location`, and `dashbuilder.export.dir` system properties to enable this new feature.

* Dashboards imported in Dashbuilder Runtime can have a default page. The following list provides a summary of dashbuilder runtime default page updates:

** When an imported dashboard has only one page, then it is used as the default page.
** If a page is named as `index` then it will be used as the default page.
** In other cases, the generic Dashbuilder Runtime home page is used.

* Dashbuilder runtime is now available with the new heatmap component feature. Heatmap is a new {CENTRAL} component that can be added to pages and be exported to Dashbuilder Runtime. Similar to a bar chart, line chart, you can drag these Heatmap components to a page and later you can export it to Dashbuilder Runtime. Heatmaps components are used to display heat information over a process diagram. The heat information can be retrieved from a {KIE_Server} datasets. You can create, edit and, build a dashboard using heatmap component.

=== Removed the case modeler technical preview editor

The case modeler technical preview editor is removed in {PRODUCT} {ENTERPRISE_VERSION}. Use the new designer for cases going forward.

For more information, see {URL_GETTING_STARTED_CASES}#assembly-getting-started-case-management[_{GETTING_STARTED_CASES}_].

endif::PAM[]

== Support for client roles in {RH-SSO}

When integrating {PRODUCT} with {RH-SSO}, you can enable support for client roles. By default, only realm roles are supported.

= KIE API improvements

You can now use the KIE REST API to signal a process using its alias.

== Integration with {AMQ_STREAMS}

You can now integrate your business processes that run on a {KIE_SERVER} with Red Hat {AMQ_STREAMS} or Apache Kafka.

== Certification of {FUSE_LONG} on {EAP}

{PRODUCT} is now certified to work with {FUSE_LONG} version 7.8 on {EAP}. Integration with {FUSE_LONG} version 7.8 on Karaf (OSGi) is not supported.

ifdef::PAM[]

== Process Designer

=== Ability to access activity details in boundary events

In the BPMN modeler, you can now set a data output in the *Data Output and Assignments* field for a boundary event. For example, you can set `nodeInstance` as a data output variable for a boundary event, which carries the node instance details to use in a further process when the boundary event is triggered.
For more information, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

=== Support for MVEL expressions in data assignments

You can now add MVEL expressions in the Data IO assignments of a user task. For more information, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

== {PROCESS_ENGINE}

=== {PROCESS_ENGINE_CAP} API improvements

You can now use the {PROCESS_ENGINE} API to signal a process instance using its correlation key.
You can now use the {PROCESS_ENGINE} API to determine the node type from within an event listener. When using the advanced query feature of the {PROCESS_ENGINE} API, you can now optionally exclude process variables from the search results.

endif::PAM[]

== {KIE_SERVER}

=== Running job failover

If you have multiple {KIE_SERVER} nodes in cluster and one node fails while in a running state, the jobs in that instance are requested to another running node.

=== Singleton timer start node

With the cluster extension, the jbpm engine now supports singleton timer start node in a process. When the extension is configured and one process is deployed in several instances, the timer start node will be only triggered once among all instances.

== Spring Boot

=== Plugable variable persistence

You can now provide an arbitrary entity manager for configured process variable persistence in your {PRODUCT} spring boot application.

== {OPENSHIFT}

=== Support for {OPENSHIFT} version 4.7

{PRODUCT} now supports {OPENSHIFT} version 4.7.

=== Support for Dashbuilder Standalone on {OPENSHIFT}

{PRODUCT} now supports Dashbuilder Standalone (dashbuilder-runtime) on {OPENSHIFT}.

=== Support for LDAP login module stacking

{PRODUCT} now supports LDAP login module stacking. You can set the `AUTH_LDAP_LOGIN_MODULE` environment variable to *optional* for LdapExtended login module images.

=== Configurable persistent volume sizes for {CENTRAL}

{PRODUCT} now supports configurable persistent volume sizes for {CENTRAL}. The default is 1Gi for {CENTRAL} and 64Mb for {CENTRAL} Monitoring.
