[id='install-download-proc_{context}']
= Downloading the {PRODUCT} installation files

Depending on your environment and installation requirements, download a {PRODUCT} distribution.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download one of the following product distributions, depending on your preferred installation method:
+
[NOTE]
====
You only need to download one of these distributions.
====
* If you want to use the installer to install {PRODUCT} on
ifeval::["{context}" == "install-on-tomcat"]
Tomcat server,
endif::[]
 download *{PRODUCT} {PRODUCT_VERSION_LONG} Installer*
ifdef::PAM[]
(`{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar`).
endif::PAM[]
ifdef::DM[]
(`{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar`).
endif::DM[]
The installer graphical user interface guides you through the installation process.

ifeval::["{context}" == "install-on-tomcat"]
* To install {KIE_SERVER} on Tomcat server using the deployableZIP files, download the following files:
** *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} Maven Repository* (`{PRODUCT_FILE}-maven-repository.zip`)
endif::[]
+
The ZIP files do not require a graphical user interface so you can install {PRODUCT} using SSH.
* To run {CENTRAL} without needing to deploy it to an application server, download *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Standalone* (`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar`).
