[id='business-central-settings-security-provider-EAP-proc']
= Configuring Wildfly or {EAP} Security provider

This security provider supports realm types based on `application-users.properties` or `application-roles.properties` properties files.

* The user, group and role implementations are provided by `org.uberfire.ext.security.management.wildfly.properties.WildflyUserManagementService` property.
* The concrete user manager implementation is `org.uberfire.ext.security.management.wildfly.properties.WildflyUserPropertiesManager` which maps the Wildfly or {EAP} users for the given realm to application users
* The concrete group manager implementation is provided by `org.uberfire.ext.security.management.wildfly.properties.WildflyGroupPropertiesManager` property.

.Prerequisites

* Wildfly or {EAP} is installed on the system.

.Procedure

If you want to use Wildfly or {EAP} security provider based on property files, do the following tasks:
If you want to use Wildfly or {EAP} security provider based on property files and CLI, do the following tasks:
