[id='business-central-settings-security-provider-tomcat-proc']
= Configuring tomcat security provider

The classes used in this package contain the user and group manager implementations for Apache Tomcat.
This provider supports realm types based on `XML` files. The default value is tomcat server, such as `tomcat-users.xml`.

* The user, group and role implementations are provided by `org.uberfire.ext.security.management.tomcat.TomcatUserManagementService` system property.
* The concrete user manager implementation is provided by `org.uberfire.ext.security.management.tomcat.TomcatUserManager` system property.
* The concrete group manager implementation is provided by `org.uberfire.ext.security.management.tomcat.TomcatGroupManager` system property.

.Prerequisites

* Tomcat is installed on the system.

.Procedure

. Create the `security-management.properties` file in the root of your application. For example, `src/main/resources/security-management.properties`.
. Enter the following keys and provider name as a value:
+
[source]
----
org.uberfire.ext.security.management.api.userManagementServices=TomcatUserManagementService
----
