[id='test-designer-create-test-template-rule-based-proc']
= Creating a test scenario template for rule-based test scenarios

Create a test scenario template for rule-based test scenarios by following the procedure below to validate your rules and data.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project for which you want to create the test scenario.
. Click *Add Asset* -> *Test Scenario*.
. Enter a *Test Scenario* name and select the appropriate *Package*. The package you select must contain all the required data objects and rule assets have been assigned or will be assigned.
. Select *RULE* as the *Source type*.
. Click *Ok* to create and open the test scenario in the test scenarios designer.
. To map the *GIVEN* column header to a data object,
.. Click an instance header in the *GIVEN* section.
.. Select the data object from the *Test Editor* tab.
.. Click *Add*.
. To insert more properties of the data object, right-click the property header and select *Insert column right* or *Insert column left* as required.
. To map a data object field to a property cell,
.. Click a property cell.
.. Select the data object field from the *Test Editor* tab.
.. Click *Add*.
. To map the *EXPECT* column header to a data object,
.. Click an instance header in the *EXPECT* section.
.. Select the data object from the *Test Editor* tab.
.. Click *Add*.
. To insert more properties of the data object, right-click the property header and select *Insert column right* or *Insert column left* as required.
. To map a data object field to a property cell,
.. Click a property cell.
.. Select the data object field from the *Test Editor* tab.
.. Click *Add*.
+
Use the contextual menu to add or remove columns as needed.
+
. To view and edit the global settings of the test scenarios, click `Settings` panel on the right side of the test scenario designer.
+
You can configure the following attributes in the `Settings` panel:
+
* `Name`: This is the name of the test scenario.
* `Type`: This attribute is read-only.
* `KieSession`: (Optinal) Enter the KieSession for the test scenario.
* `RuleFlowGroup/AgendaGroup`: (Optinal) Enter the RuleFlowGroup or AgendaGroup for the test scenario.
* Select the check box to skip the simulation during the test.
. Click `Save`.

After you have created and mapped both the *GIVEN* & *EXPECT* columns to a data object & its properties, you have to define the test scenario which comes next.
